version: '3.8'

services:
  postgres:
    image: postgres-db:latest
    environment:
      POSTGRES_PASSWORD: 05112003
    ports:
      - "5432:5432" 

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
